const Data = [
    {
    id : "1",
        url: "/images/bird.jpg",
        name: "Wild Bird",
        history: "Birds are descendants of theropod dinosaurs, a group of bipedal saurischian dinosaurs. The most famous early bird is Archaeopteryx, which lived about 150 million years ago during the Late Jurassic period. Archaeopteryx had both avian and reptilian features, including feathers, wings, and a wishbone (avian characteristics), as well as teeth, a long bony tail, and clawed fingers (reptilian characteristics). This fossil provided critical evidence for the evolutionary transition from dinosaurs to birds.During the Mesozoic Era, particularly in the Cretaceous period, birds began to diversify. Early birds were small, with limited flying abilities, but over time they developed better flight mechanisms. The evolution of flight likely played a significant role in their survival, as it allowed them to escape predators, travel long distances, and exploit new ecological niches.Around 66 million years ago, a mass extinction event wiped out about 75% of Earth's species, including most dinosaurs. However, some bird species survived, particularly those that lived in aquatic environments or had more adaptable diets. These survivors gave rise to the vast diversity of birds we see today.After the extinction event, birds rapidly diversified during the Cenozoic Era. They evolved into a wide range of forms and sizes, occupying nearly every ecological niche on Earth. This era saw the emergence of many modern bird families and orders. Notable developments include the evolution of large flightless birds like ostriches and emus, as well as highly specialized birds such as hummingbirds and penguins.Today, birds are among the most diverse vertebrate groups, with over 10,000 species worldwide. They exhibit an incredible range of adaptations, from the powerful talons of raptors to the specialized beaks of finches. Birds have also played significant roles in human culture, mythology, and science.",
    },
    {
        id : "2",
        url: "/images/cat.jpg",
        name: "Cat",
        history: "Domestic cats (Felis catus) are believed to have descended from the African wildcat (Felis silvestris lybica). This wildcat species is still found in parts of Africa, the Middle East, and Asia.Around 9,000 years ago, wildcats began to frequent human settlements, attracted by the abundance of food sources such as rodents that thrived near grain stores.The earliest evidence of cat domestication dates back to around 7500 BCE in Cyprus, where a cat was found buried alongside a human. This suggests that cats had a special relationship with humans even in ancient times.The domestication of cats likely began in the Near East's Fertile Crescent, where agriculture first developed. As humans settled into agrarian communities, cats played a crucial role in controlling the rodent population, thus earning their place in human society.Cats held a revered status in ancient Egypt, where they were associated with the goddess Bastet, the deity of home, fertility, and protection.Killing a cat, even accidentally, was punishable by death. Cats were often mummified and buried with their owners to accompany them in the afterlife.By 1500 BCE, cats had become fully domesticated and spread across Egypt.From Egypt, cats spread to Greece and Rome. The Romans were particularly fond of cats and helped spread them throughout Europe.Cats were appreciated for their hunting skills, which protected food supplies from pests.",
    },
    {
        id : "3",
        url: "/images/chicken.jpg",
        name: "Farm Animal",
        history: "The history of farm animals is deeply intertwined with the development of human civilization.From the domestication of wild species to the complex breeding practices of today, farm animals have played a crucial role in agriculture, culture, and economies across the world.Cattle are among the earliest animals to be domesticated, with evidence suggesting they were tamed around 10,000 years ago in the Fertile Crescent, a region in the Near East. Descended from wild aurochs, domesticated cattle were initially valued for their meat, milk, and hides. These animals were also domesticated in the Fertile Crescent roughly 11,000 years ago. They were prized for their wool, meat, and milk. Sheep and goats are particularly hardy, making them ideal for various environments, from deserts to mountains.Domesticated around 9,000 years ago in Asia, pigs evolved from wild boars. Pigs were valued for their meat and their ability to thrive on a wide range of foodstuffs, including agricultural by-products. Horses were domesticated in the steppes of Central Asia around 4,000 years ago. Initially used for meat and milk, they later became crucial for transportation, warfare, and agriculture.Chickens were first domesticated in Southeast Asia over 7,000 years ago. They were initially raised for cockfighting and only later for their eggs and meat.The domestication of oxen, horses, and donkeys revolutionized agriculture by providing draft power for plowing fields, transporting goods, and turning mills. This greatly increased agricultural productivity.Farm animals became a primary source of food, providing meat, milk, eggs, and other products. Dairy cattle, in particular, became essential in many cultures, contributing to the development of various dairy products."
    },
    {
        id : "4",
        url: "/images/dog1.jpg",
        name: "Dog",
        history: "The history of dogs is a fascinating tale that spans thousands of years, from their wild ancestors to their role as man's best friend.Dogs are descendants of wolves, with genetic evidence indicating that domestication began around 20,000 to 40,000 years ago. Early humans likely formed a mutually beneficial relationship with wolves, which eventually led to domestication. Wolves provided early humans with protection and assistance in hunting, while humans provided food and shelter.The exact timeline of domestication is debated, but it is generally believed that dogs were the first domesticated animals. This process may have begun when wolves started scavenging near human campsites, leading to a gradual selection for traits such as reduced aggression and increased sociability. Over time, these wolves evolved into a new species—dogs (Canis lupus familiaris). Dogs played various roles in ancient societies. In Mesopotamia, Egypt, and Greece, dogs were revered for their hunting skills, loyalty, and ability to guard homes. The Egyptians even mummified dogs and included them in their burial rites.As humans migrated and established civilizations, they began selectively breeding dogs for specific tasks. This led to the development of various breeds tailored for hunting, herding, guarding, and companionship. By the time of the Roman Empire, dogs were classified into different types based on their function, such as war dogs, hunting dogs, and lapdogs.The 19th century saw the establishment of kennel clubs and the standardization of dog breeds. The first dog show took place in 1859 in Newcastle, England. The American Kennel Club (AKC) was founded in 1884, marking a significant shift towards organized breeding and the promotion of purebred dogs.The role of dogs began to shift more towards companionship during the Victorian era, with an emphasis on their presence in family life. This trend continued into the 20th century, with dogs becoming an integral part of the household.",
    },
    {
        id : "5",
        url: "/images/fish.jpg",
        name: "Fish",
         history: "Fish are among the oldest vertebrates on Earth. Their origins date back to the Cambrian period, around 500 million years ago. The first fish were jawless, resembling modern lampreys and hagfish. These early fish, known as agnathans, had simple, elongated bodies and were mostly small in size.The evolution of fish began in the oceans, which were teeming with diverse forms of life. Early fish had cartilaginous skeletons and lacked true jaws, making them different from most modern fish.Around 420 million years ago, during the Silurian period, fish with jaws appeared. These jawed fish, known as gnathostomes, marked a significant evolutionary advancement, as jaws allowed them to catch and consume a wider variety of prey.Two major groups of jawed fish emerged: placoderms (armored fish) and cartilaginous fish (ancestors of modern sharks and rays). Placoderms eventually went extinct, but cartilaginous fish continued to thrive.Bony fish, or osteichthyans, evolved around 400 million years ago during the Devonian period. These fish had skeletons made of bone, which provided better support and allowed for more diverse forms and sizes.Bony fish are divided into two major groups: lobe-finned fish and ray-finned fish. Lobe-finned fish are the ancestors of tetrapods (four-limbed animals, including amphibians, reptiles, birds, and mammals), while ray-finned fish are the ancestors of most modern fish species.Over millions of years, fish diversified into a wide range of species, adapting to various environments from freshwater rivers and lakes to deep oceanic trenches. Some fish developed specialized adaptations, such as electric organs, bioluminescence, and the ability to live in extreme conditions.The rise of coral reefs around 250 million years ago provided new habitats, leading to further diversification of fish species, particularly in the tropics.",
    },
    {
        id : "6",
        url: "/images/horse2.jpg",
        name: "Horse",
         history: "Horses have played a crucial role in human history, serving as companions, tools for labor, and instruments of war. Their evolution and domestication have significantly shaped civilizations and cultures around the world. The earliest known ancestor of the modern horse, Eohippus, lived around 55 million years ago during the Eocene epoch. This small, dog-sized animal had multiple toes and lived in forested environments.Over millions of years, Eohippus evolved into Mesohippus, which had three toes on each foot and was larger in size.Merychippus marked a significant step toward modern horses. It was larger and had a more developed middle toe, which eventually evolved into the hoof. This genus is considered the closest ancestor of the modern horse. Pliohippus had a single toe and was more adapted to running on open grasslands.The domestication of horses likely occurred on the steppes of Central Asia, particularly in modern-day Ukraine, southwestern Russia, and western Kazakhstan. The Botai culture in Kazakhstan is one of the earliest known groups to have domesticated horses.Domesticated horses quickly spread across Europe, Asia, and the Middle East, playing a vital role in transportation, agriculture, and warfare. Horses were first used in warfare to pull chariots. The development of the chariot revolutionized warfare in the ancient world, giving rise to powerful chariot armies in civilizations like Egypt, Mesopotamia, and China.The use of horses as cavalry began to emerge, with mounted warriors becoming key components of armies. The Scythians, Persians, and later the Mongols perfected cavalry warfare, using horses for speed, mobility, and shock tactics.Horses have been revered in various cultures, symbolizing power, freedom, and nobility. They appear in mythology and religion, from the winged Pegasus in Greek mythology to the warhorse of the Hindu god Kalki.Horses have been central to many sports and recreational activities, including horse racing, polo, and equestrian competitions. These activities date back to ancient times and continue to be popular today. Over the centuries, horses have been selectively bred for specific purposes, leading to the development of various breeds. These include draft horses for heavy work, light horses for riding, and ponies for smaller tasks.With the advent of motorized vehicles and machinery in the 20th century, the practical use of horses in transportation and agriculture declined. However, horses remain important in sport, recreation, and certain traditional practices.While their role in everyday work has diminished, horses are still highly valued. Conservation efforts have been made to preserve rare breeds and maintain the cultural heritage associated with horses.",
    },
    {
        id : "7",
        url: "/images/parrot.jpg",
        name: "Parrot",
         history: "Parrots are a diverse group of birds belonging to the order Psittaciformes, which includes over 400 species. These colorful and intelligent birds have a long history that stretches back millions of years.The oldest known parrot fossils date back about 50 million years, found in Europe. These early parrots resembled modern species but lived in subtropical and tropical forests that covered much of the world during that period.Parrots are believed to have evolved in the Southern Hemisphere, particularly in regions that are now part of Australia, South America, and Africa. Their evolutionary ancestors likely originated in Gondwana, the ancient supercontinent.Parrots have been revered by many cultures throughout history. In ancient Egypt, parrots were kept as pets by royalty. In the Hindu and Buddhist traditions of India, parrots were seen as sacred, often associated with gods and wisdom. The Mayans and Aztecs of Central America considered parrots sacred and used their feathers in ceremonial headdresses and rituals. Parrots were also traded across vast distances, from South America to Mesoamerica, as their vibrant feathers were highly prized.Parrots were first introduced to Europe during the time of Alexander the Great, who is said to have brought back Indian Ringneck Parakeets from his campaigns in Asia. However, parrots became more widespread in Europe during the Age of Exploration in the 15th and 16th centuries, when European explorers and colonizers brought them back from the Americas, Africa, and the Pacific Islands. During the Renaissance and the Enlightenment, parrots became popular pets among the European elite. Their ability to mimic human speech and their striking appearance made them symbols of luxury and exoticism. Today, many parrot species face threats from habitat loss, the illegal pet trade, and climate change. Some species, like the Spix's Macaw, have become extinct in the wild, while others are critically endangered. Conservation efforts are underway to protect these birds, including habitat preservation, breeding programs, and legal protections.Parrots continue to be popular as pets worldwide, known for their intelligence, social nature, and ability to mimic sounds. They also play a significant role in popular culture, appearing in literature, films, and art.",
    },
    {
        id : "8",
        url: "/images/reptile.jpg",
        name: "Reptile",
        history: "The earliest ancestors of reptiles were part of a group of animals known as tetrapods, which were the first vertebrates to move onto land. These early tetrapods evolved from lobe-finned fishes and gradually adapted to terrestrial life.Carboniferous Period (about 320-300 million years ago): The first true reptiles appeared during the late Carboniferous period. These early reptiles were small, lizard-like creatures. The development of the amniotic egg was a significant evolutionary advance, allowing reptiles to reproduce on land without returning to water, unlike amphibians. Reptiles began to diversify during the Permian, giving rise to various groups, including the ancestors of modern reptiles, mammals, and the earliest archosaurs (which would later evolve into dinosaurs, pterosaurs, and crocodiles).After the Permian mass extinction, reptiles became the dominant land animals. The Triassic saw the emergence of the first dinosaurs, as well as the first true crocodiles and the earliest turtles.Dinosaurs flourished during the Jurassic, with large herbivorous dinosaurs like sauropods and predatory dinosaurs like Allosaurus dominating the landscape. This period also saw the rise of the first birds, which evolved from small theropod dinosaurs. Reptiles continued to dominate during the Cretaceous, with dinosaurs reaching their peak diversity. The period ended with the Cretaceous-Paleogene (K-Pg) extinction event, which wiped out the non-avian dinosaurs and many other species.After the extinction of the dinosaurs, mammals began to rise, but reptiles continued to thrive in various niches. Crocodiles, turtles, and lizards diversified, and snakes became more prominent.Reptiles have continued to evolve, with modern groups such as snakes, lizards, turtles, and crocodiles adapting to a wide range of environments. The evolution of modern birds from theropod dinosaurs is one of the most significant events in the history of reptiles.Today, reptiles are represented by four main groups:Squamates (lizards and snakes): The largest group of reptiles, with thousands of species adapted to a variety of habitats.Testudines (turtles and tortoises): Known for their bony or cartilaginous shells, they inhabit diverse environments from oceans to deserts.Crocodylians (crocodiles, alligators, caimans): Semi-aquatic predators that have changed little since the time of the dinosaurs.Rhynchocephalians (tuatara): A small group represented by a single living species, the tuatara, found in New Zealand.",
    },
    {
        id : "9",
        url: "/images/squirrel2.jpg",
        name: "Squirrel",
         history: " Squirrels are part of the order Rodentia, which is one of the oldest groups of mammals. The earliest known ancestors of modern squirrels appeared around 40-50 million years ago, during the Eocene Epoch. These early rodents were small, tree-dwelling creatures that eventually gave rise to the diverse group of squirrels we see today. By the Miocene, squirrels had diversified into several genera. Fossil evidence from this period shows that many of the characteristics we associate with modern squirrels, such as strong hind legs and bushy tails, had already evolved.Squirrels are native to the Americas, Eurasia, and Africa, and they have adapted to a wide range of habitats, from dense forests to urban areas. There are over 200 species of squirrels, divided into three main categories:Tree Squirrels: The most common and well-known type, including species like the Eastern Gray Squirrel.Ground Squirrels: Including chipmunks and prairie dogs, these squirrels are adapted to life on the ground and burrowing.Flying Squirrels: These nocturnal squirrels have a membrane called the patagium that allows them to glide between trees.Squirrels have evolved various adaptations to thrive in different environments. Their sharp claws and strong legs make them excellent climbers, while their keen sense of smell and vision help them detect food and predators. Flying squirrels, with their gliding ability, have adapted to nocturnal life in forests.Squirrels have been a part of human culture for centuries. In some Native American traditions, squirrels are considered messengers or symbols of preparation and activity. In Norse mythology, a squirrel named Ratatoskr runs up and down Yggdrasil, the World Tree, carrying messages between the eagle at the top and the serpent at the bottom.While many squirrel species are thriving, some are endangered due to habitat loss and competition with invasive species. For example, the Red Squirrel in the UK has been severely affected by the introduction of the Eastern Gray Squirrel, leading to conservation efforts to protect the native species.",
    },
]

export default Data